### ISSUE TITLE
A documentation clarification

### ISSUE THREAD

**Issue by boshek** [clauswilke/ggjoy#14]
Incredible package. Thank you.

The @description of `geom_ridgeline` states (emphasize added): 

> Plots the sum of the y and height aesthetics versus x, filling the area between y and y + height with a color. **Thus, the data mapped onto y and onto height must be in the same units**. If you want relative scaling of the heights, you can use geom_joy with stat = "identity".

Is it possible to elaborate on this at all? If we set height in `geom_ridgeline` like this:
```
library(ggplot2)
library(ggjoy)

d <- data.frame(x = rep(1:5, 3), Year = c(rep(1979, 5), rep(1980, 5), rep(1981, 5)),
                height = c(0, 1, 3, 4, 0, 1, 2, 3, 5, 4, 0, 5, 4, 4, 1))

ggplot(d, aes(x, y = Year, height = height, group = Year)) + 
  geom_ridgeline(scale = 0.2) 
```
We get this plot: 
![image](https://user-images.githubusercontent.com/18472598/28641607-b9bfdab0-7204-11e7-8004-6aa9a428454b.png)

Using different scales for y and height seem to be an issue. But if do something like this with `geom_joy` it is ok:
```
ggplot(d, aes(x, y = Year, height = height, group = Year)) + 
  geom_joy(stat = "identity", scale = 1)
```
![image](https://user-images.githubusercontent.com/18472598/28641675-f08b699c-7204-11e7-90e1-669156b776b1.png)
Now obviously I am missing something because these are the same plot. However there is no similar stipulation the the `ggjoy` documentation. So my question is one of convention. When using ggjoy, if we are plotting raw data and stacking them, it is best to use the same variable as y but if we are plotting data distributions, it is ok to deviate from this rule because density (or count) is assumed? For example:
`ggplot(iris, aes(x = Sepal.Length, y = Species)) + geom_joy()`
![image](https://user-images.githubusercontent.com/18472598/28641893-738a1bd6-7205-11e7-8ccd-5bedb2ecee40.png)

My goal is to plot a time series where I set height to continuous variable, plot a year on the y-axis and then plot day-month on the x-axis. This provides a VERY nice visualization of data by year. I can do this (basically the 1st or 2nd example). However the documentation has thrown me and I wanted to make sure that I was on the right side visualization conventions. So ultimately the question is, in what instances, if any,is it ok for the `height` and `y` argument to be of different scales?

**Comment by clauswilke** [comment]
`geom_ridgeline` plots `y+scale*height` and `geom_joy` plots `y+norm*scale*height` where `norm` is an internal normalization factor that is calculated so that `scale=1` will generally cause the tallest curve to just touch the next higher curve.

So, with  `geom_ridgeline`, you have to set `scale` yourself to the appropriate value, while with `geom_joy` you can generally assume that the lines just touch for `scale=1`, overlap for `scale>1`, and have some padding for `scale<1`. In most applications, `geom_joy` is probably preferable, though both geoms will ultimately produce the same plots if the `scale` factor is appropriately adjusted.
